### ISSUE TITLE
Make getter/setters to fit RFC 344

### ISSUE THREAD

**Issue by Fullstop000** [Fullstop000/wickdb#4]
Relative link [RFC/0344](https://github.com/rust-lang/rfcs/blob/master/text/0344-conventions-galore.md#gettersetter-apis).

Clearly, we just need to rename `set_` methods in normal structs.

**Comment by Hoverbear** [comment]
You might be able to reduce some boilerplate with https://github.com/Hoverbear/getset/ :)
